# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)
owner_name="veda59-gmail.com"
app_name="vedcircleciproj"
project_name="vedtestprojecicd"
path = "./#{project_name}.xcodeproj"

platform :ios do

before_all do
    setup_circle_ci
    create_keychain(
      name: "vedyoooo",
      password: "veddd123@",
      default_keychain: true,
      unlock: true
    )
  end

desc "Bump build number"
  lane :bump_version do
    increment_build_number(
      xcodeproj: path,
      build_number: Time.now.strftime("%y%m%d%H%M") # ENV['CIRCLE_BUILD_NUM']
    )
  end

  desc "Upload to AppCenter"
  lane :upload_to_appcenter do | options |
    appcenter_upload(
      owner_name: owner_name,
      app_name:  app_name
    )
  end
  
  desc "Update the devices with the ones in devices.txt"
  lane :update_devices do
    register_devices(
      devices_file: "./devices.txt"
    )
  end

  desc "register a device on apple dev portal"
  lane :register_dev_device do |options|
    register_devices(
      devices: {
        options[:name] => options[:udid]
      },
      username: "veda59@gmail.com"
    )
  end


  desc "Push a new release build to the App Store"
  lane :release do
  update_devices
    increment_build_number(xcodeproj: "vedtestprojecicd.xcodeproj")
    cert(filename: './newcer.cer', keychain_password: "veddd123@", keychain_name: "vedyoooo")
    sigh(force:true)
    build_app(workspace: "vedtestprojecicd.xcworkspace", scheme: "vedtestprojecicd")
    #upload_to_app_store(skip_metadata: true, skip_screenshots: true)
    upload_to_appcenter(
      app_name:  "vedtestprojecicd"
    )
  end
end
